version: '2'
services:
  h241-app:
    image: h241
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://h241-postgresql:5432/H241
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  h241-postgresql:
    extends:
      file: postgresql.yml
      service: h241-postgresql
